### ISSUE TITLE
last version beta 4

### ISSUE THREAD

**Issue by miztizm** [WebCrew/HumHub-Music-Player#2]
PHP Parse Error – yii\base\ErrorException

syntax error, unexpected '?>', expecting function (T_FUNCTION)

**Comment by Felli** [comment]
Just to let you know this module isn't ready yet.

**Comment by miztizm** [comment]
its abandoned or just not ready.? Thank you for your answer.

**Comment by Felli** [comment]
Just not ready for use, from what I can tell the owner still has some work to do on it before it's 100% ready for use. :smile:

**Comment by WebCrew** [comment]
Yes the module is na work in progress and it first needs a person with Yii knowledge to get it finished.
